authentication/urls.py
from django.urls import path
from authentication.views import (
		SignUpView,SignInView,SignOutView,PRView,PRConfirm,PRDone,PRComplete,PWDChangeView,PWDChangeDoneView,
	)
urlpatterns=[
	# path('home/',home,name='home'),
	path('signin/',SignInView.as_view(),name='signin_view'),
	path('signup/',SignUpView.as_view(),name='signup_view'),
	path('signout/',SignOutView.as_view(),name='signout_view'),
	path('password/reset/',PRView.as_view(),name='password_reset'),
	path('password/reset/done/',PRDone.as_view(),name='password_reset_done'),
	path('password/reset/confirm/<uidb64>/<token>',PRConfirm.as_view(),name='password_reset_confirm'),
	path('password/reset/complete',PRComplete.as_view(),name='password_reset_complete'),
	path('password/change/', PWDChangeView.as_view(),name='password_change_view'),
	path('password/change/done', PWDChangeDoneView.as_view(),name='password_change_done_view'),

]

lbm/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authentication.urls')),
    path('',include('core.urls')),
    path('',include('user.urls')),
]


urlpatterns.extend(
    static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

    )

authentication/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from crum import get_current_user

from django.contrib.auth import get_user_model

# Create your models here.

RETURN_CHOICES = [
    ('Yes', 'Yes'),
    ('No', 'No'),
]

User = get_user_model()

class Student(models.Model):
	name=models.CharField(max_length=100)
	department=models.CharField(max_length=100)
	user=models.OneToOneField(User,related_name='student_reg',on_delete=models.CASCADE,null=True)
	created_on=models.DateTimeField(auto_now_add=True)
	updated_on=models.DateTimeField(auto_now=True)

	class Meta:
		ordering=['-created_on']

	def save(self, *args, **kwargs):
		user = get_current_user()
		if user and not user.pk:
			user = None
		if not self.pk:
			self.user = user

		super(Student, self).save(*args, **kwargs)

class Teacher(models.Model):
	name=models.CharField(max_length=100)
	user=models.OneToOneField(User,related_name='teacher_reg',on_delete=models.CASCADE,null=True)
	created_on=models.DateTimeField(auto_now_add=True)
	updated_on=models.DateTimeField(auto_now=True)

	class Meta:
		ordering=['-created_on']

	def __str__(self):
		return str(self.name)

	def save(self, *args, **kwargs):
		user = get_current_user()
		if user and not user.pk:
			user = None
		if not self.pk:
			self.user = user

		super(Teacher, self).save(*args, **kwargs)


class Book(models.Model):
	name=models.CharField(max_length=150)
	author=models.CharField(max_length=100)
	publication=models.CharField(max_length=200)
	publication_year=models.DateTimeField()
	created_on=models.DateTimeField(auto_now_add=True)
	updated_on=models.DateTimeField(auto_now=True)

	class Meta:
		ordering=['-created_on']

	def __str__(self):
		return str(self.name)

class BookIssue(models.Model):
	sudent=models.ForeignKey(Student,on_delete=models.CASCADE,null=True)
	book=models.ForeignKey(Book,on_delete=models.CASCADE,null=True)
	penality=models.IntegerField(default=0)
	book_return=models.CharField(max_length=50,choices=RETURN_CHOICES,null=True,blank=True)
	created_on=models.DateTimeField(auto_now_add=True)
	updated_on=models.DateTimeField(auto_now=True)


	class Meta:
		ordering=['-created_on']

	def __str__(self):
		return str(self.student)

class Event(models.Model):
	event_name=models.CharField(max_length=100)
	event_description=models.TextField()
	created_on=models.DateTimeField(auto_now_add=True)
	updated_on=models.DateTimeField(auto_now=True)

	class Meta:
		ordering=['-created_on']

	def __str__(self):
		return str(self.event_name)

class Due(models.Model):
	book_issue=models.ForeignKey(BookIssue,on_delete=models.CASCADE,null=True)
	payment=models.IntegerField()
	created_on=models.DateTimeField(auto_now_add=True)
	updated_on=models.DateTimeField(auto_now=True)

	class Meta:
		ordering=['-created_on']

	def __str__(self):
		return str(self.book_issue)




class Contact(models.Model):
	email=models.EmailField(max_length=50)
	user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
	description=models.CharField(max_length=300)
	reply=models.CharField(max_length=255)
	created_on=models.DateTimeField(auto_now_add=True)
	updated_on=models.DateTimeField(auto_now=True)

	class Meta:
		ordering=['-created_on']

	def __str__(self):
		return str(self.email)

	def save(self, *args, **kwargs):
		user = get_current_user()
		if user and not user.pk:
			user = None
		if not self.pk:
			self.user = user

		super(Contact, self).save(*args, **kwargs)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from user.managers import CustomUserManager
# # Create your models here.


GENDER_CHOICES = [
    ('M', 'Male'),
    ('F', 'Female'),
    ('None', 'Prefer not to say.'),
]


class User(AbstractUser):
    picture = models.ImageField(upload_to='profile_pictures', null=True, blank=True)
    full_name = models.CharField(max_length=100, help_text='Help people discover your account by using the name you\'re known by: either your full name, nickname, or business name.')
    email = models.EmailField(unique=True)

    # Optional fields
    bio = models.TextField(null=True, blank=True, help_text='Provide your personal information, even if the account is used for a business, a pet or something else. This won\'t be a part of your public profile.')
    website = models.URLField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, null=True, blank=True)
    is_private_account = models.BooleanField(default=False)

    first_name = None
    last_name = None

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name','username',]

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class UserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('full_name', 'email', 'username', 'password1', 'password2')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('full_name', 'email', 'username',)

authentication/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from authentication.forms import UserForm
from django.contrib import messages
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout,get_user_model
from django.contrib.auth.views import (
	PasswordResetView,
	PasswordResetConfirmView,
	PasswordResetDoneView,
	PasswordResetCompleteView,
	PasswordChangeView,
	PasswordChangeDoneView,

	)

# Create your views here.

User=get_user_model()



class SignInView(View):
	template_name='authentication/signin.html'

	def get(self,request,*args,**kwargs):
		if request.user.is_authenticated:
			return redirect('user_feed_view')
		return render(request,self.template_name)
		
	
	def post(self,request,*args,**kwargs):
		email=request.POST.get('email')
		password=request.POST.get('password')


		try:
			user_obj=User.objects.get(username=email)
			email=user_obj.email

		except Exception as e:
			email=email

		user=authenticate(request,email=email,password=password)
		if user is None:
			messages.error(request,"Invalid Login ",extra_tags="error")
			return render(request,self.template_name)
		login(request,user)
		return redirect('user_feed_view')



class SignUpView(View):
	template_name='authentication/signup.html'
	form_class=UserForm

	def get(self,request,*args,**kwargs):
		if request.user.is_authenticated:
			return redirect('user_feed_view')
		return render(request,self.template_name)

	def post(self,request,*args,**kwargs):
		form=self.form_class(request.POST)
		if form.is_valid():
			form.save()
			return redirect('signin_view')

		context={'form':form}

		return render(request,self.template_name,context)


class SignOutView(View):
	def post(self,request,*args,**kwargs):
		logout(request)
		return redirect('homepage')

class PRView(PasswordResetView):
	template_name='authentication/password_reset.html'
	email_template_name='authentication/password_reset_email.html'


class PRConfirm(PasswordResetConfirmView):
    template_name='authentication/password_reset_confirm.html'

class PRDone(PasswordResetDoneView):
	template_name='authentication/password_reset_done.html'

class PRComplete(PasswordResetCompleteView):
	template_name='authentication/password_reset_complete.html'

class PWDChangeView(PasswordChangeView):
	template_name='authentication/password_change.html'
	success_url=reverse_lazy('password_change_done_view')

class PWDChangeDoneView(PasswordChangeDoneView):
	template_name='authentication/password_change_done.html'

authentication/templates/authentication/base.html
{% load static %}
<!doctype html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrapmin4.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    
    {% block extra_head %}{% endblock %}
    

    <title>Library Management System</title>
  </head>
  <body>

    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    {% block extra_body %}{% endblock %}

  </body>
</html>

authentication/templates/authentication/login.html
{% load static %}
<!doctype html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles/bootstrapmin4.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'styles/login.css' %}">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    

    <title>Library Management System</title>
  </head>
  <body>

    <div class="container-fluid pr-0 pl-0">
    <div class="card ">
        <div class="row d-flex">
            <div class="col-lg-6">
                <div class="card1 ">
                    <div class="row"> <img src="https://i.imgur.com/CXQmsmF.png" class="logo"> </div>
                    <div class="row px-3 justify-content-center mt-4 mb-5 border-line"> <img src="https://i.imgur.com/uNGdWHi.png" class="image"> </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card2 card border-0 px-4 py-5">
                    <div class="row mb-4 px-3">
                        <h6 class="mb-0 mr-4 mt-2">Sign in with</h6>
                        <div class="facebook text-center mr-3">
                            <div class="fa fa-facebook"></div>
                        </div>
                        <div class="twitter text-center mr-3">
                            <div class="fa fa-twitter"></div>
                        </div>
                        <div class="linkedin text-center mr-3">
                            <div class="fa fa-linkedin"></div>
                        </div>
                    </div>
                    <div class="row px-3 mb-4">
                        <div class="line"></div> <small class="or text-center">Or</small>
                        <div class="line"></div>
                    </div>
                    <div class="row px-3"> <label class="mb-1">
                            <h6 class="mb-0 text-sm">Email Address</h6>
                        </label> <input class="mb-4" type="text" name="email" placeholder="Enter a valid email address"> </div>
                    <div class="row px-3"> <label class="mb-1">
                            <h6 class="mb-0 text-sm">Password</h6>
                        </label> <input type="password" name="password" placeholder="Enter password"> </div>
                    <div class="row px-3 mb-4">
                        <div class="custom-control custom-checkbox custom-control-inline"> <input id="chk1" type="checkbox" name="chk" class="custom-control-input"> <label for="chk1" class="custom-control-label text-sm">Remember me</label> </div> <a href="#" class="ml-auto mb-0 text-sm">Forgot Password?</a>
                    </div>
                    <div class="row mb-3 px-3"> <button type="submit" class="btn btn-blue text-center">Login</button> </div>
                    <div class="row mb-4 px-3"> <small class="font-weight-bold">Don't have an account? <a class="text-danger ">Register</a></small> </div>
                </div>
            </div>
        </div>
        <div class="bg-blue py-4">
            <div class="row px-3 "> <small class="ml-4 ml-sm-5 mb-2">Copyright &copy; 2019. All rights reserved.</small>
                <div class="social-contact ml-4 ml-sm-auto"> <span class="fa fa-facebook mr-4 text-sm"></span> <span class="fa fa-google-plus mr-4 text-sm"></span> <span class="fa fa-linkedin mr-4 text-sm"></span> <span class="fa fa-twitter mr-4 mr-sm-5 text-sm"></span> </div>
            </div>
        </div>
    </div>
</div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
   

  </body>
</html>

authentication/templates/authentication/password_change.html
{% extends 'core/feed/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/password_change.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row ">
            <div class="col-12 my-4">
                <div class="card password__change__card m-auto">
                    <div class="card-header">
                        <p class="m-0" style="color: #5f5f5f;">Change Password</p>
                    </div>
                    <div class="card-body offset-md-2">
                        <form method="POST">
                            {% csrf_token %}

                            <!-- Password Change Form -->
                            {% for field in form %}
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label col-form-label-sm text-md-right font-weight-bolder" for="{{ field.auto_id }}">
                                        {{ field.label }}
                                    </label>
                                    <div class="col-sm-8">
                                        {{ field }}
                                        <small id="passwordHelpBlock" class="form-text text-muted">
                                            {{ field.help_text }}
                                        </small>
                                        <div class="{% if field.errors %}validation__error{% else %}invalid-feedback{% endif %}">
                                            {{ field.errors }}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                            <!-- End Password Change Form -->

                            <div class="offset-md-2 my-1">
                                <button class="btn btn-sm btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
    <div style="height:10vh;">
    </div>
{% endblock %}

authentication/templates/authentication/password_change_done.html
{% extends 'core/feed/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/authentication/password_change.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12 my-4">
                <div class="card password__change__card m-auto">
                    <div class="text-center p-5">

                        <!-- Password Changed Success Message -->
                        <p class="text-muted">Congratulations, your password has been successfully changed. <a href="{% url 'profile_view' request.user.username %}">Go Back to Profile</a>
                        </p>
                        <!-- End Password Changed Success Message -->

                    </div>                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/password_reset.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/password_reset.css' %}">
{% endblock %}

{% block content %}

<header>
    <!-- <nav class="navbar navbar-light bg-white border-bottom">
        <div class="container">
            <a class="navbar-brand" href="/">
                <img src="{% static 'img/reset.' %}" class="nav__insta__logo">
            </a>
        </div>
    </nav> -->
</header>

<div class="container my-5">
    <div class="row">
        <div class="col-sm-12 my-auto">
            <div class="text-center card px-5 mx-auto auth__card">
                <img src="{% static 'img/reset.png' %}" class="insta__logo mx-auto mt-3 mb-4">
                <div class="">
                    <div class="text-center"><h4 class="trouble__signin__in">Trouble Signin In?</h4></div>
                    <div class="forgot__password__text py-2">
                        Enter your email, phone, or username and we'll send you a link to get back into your account.
                    </div>
                    <div class="mb-3">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="my-1 form__input">
                                <input id="id_email" type="email" name="email" placeholder="Email" required maxlength="240" autocomplete="email">
                            </div>
                            <div class="my-4 mx-auto text-center">
                                <button class="btn btn-sm auth__btn">Send Signin Link</button>
                            </div>
                        </form>
                    </div>
                    <div class="text-center my-4">
                        <p class="or__text">OR</p>
                    </div>
                    <div class="text-center mx-auto mb-5">
                        <a class="links__to__page text-decoration-none" href="{% url 'signup_view' %}">
                            Create New Account
                        </a>
                    </div>
                </div>
            </div>
            <div class="text-center card px-5 mx-auto auth__card bg-light mt-2">
                <a class="links__to__page p-2 text-decoration-none" href="{% url 'signin_view' %}">Back To Signin</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

authentication/templates/authentication/password_reset_email.html
Devjunction is trying to steal your pasword- {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

authentication/templates/authentication/signin.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/signin.css' %}">

{% endblock %}

{% block content %}

<div class="container my-5 ">
    
        <div class=" col-sm-4 my-auto mx-auto">
            
                <div class="text-center card px-5  ">
                    <h2 class=" mt-4 mb-3 mx-auto">Sign In</h2>
                    <div class="signin">
                        <div class="signin__form mb-3">
                            {%if messages %}
                                {% for message in messages %}
                            <div class="alert alert-danger" role='alert'>
                                    {{message}}
                            </div>
                                {% endfor %}
                            {% endif %}
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                              <div class="input-group-text" id="btnGroupAddon"><i class="bi bi-telegram"></i></div>
                            </div>

                                  
                                    <input id="id_email" type="email" name="email" placeholder="Email" class="form-control ">
                                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend">
                              <div class="input-group-text" id="btnGroupAddon"><i class="bi bi-key-fill"></i></div>
                            </div>
                                   
                                    <input id="id_password1" type="password" name="password" placeholder="Password" class="form-control">
                                    
                                </div>
                            </div>
                                
                                <div class="my-4 mx-auto text-center">
                                    <button class="btn btn-sm auth__btn">Sign in</button>
                                </div>
                            </form>
                        </div>
                        <div class="text-center my-4">
                            <p class="or__text">OR</p>
                        </div>
                        <div class="my-1 mx-auto text-center">
                            <a class="login__fb__text text-decoration-none" href="/">Log in with Facebook</a>
                        </div>
                        
                        <div class="mb-4">
                            <a class="forogt__password text-decoration-none" href="{% url 'password_reset' %}">Forgot password?</a>
                        </div>
                    </div>
                </div>
                <div class="text-center card mt-2 px-5  ">
                    <p class="have__an__account py-3">Don't have an account? <a href="{% url 'signup_view' %}" class="text-decoration-none">Sign up</a></p>
                </div>
                <!-- <div class="text-center mt-2 px-2">
                    <p class="">Get the app.</p>
                    <div class="row">
                        <div class="col-4">
                            <img src="{% static 'img/appstore.png' %}" class="app__download__img">
                        </div>
                        <div class="col-4">
                            <img src="{% static 'img/playstore.png' %}" class="app__download__img">
                        </div>
                    </div>
                </div> -->
            </div>
       
    
</div>

{% endblock %}

authentication/templates/authentication/signup.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'styles/signup.css' %}">

{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row">
        <div class="col-sm-4 offset-md-4 my-auto ">
                <div class="text-center card px-5 mx-auto ">
                     <h2 class="mt-4 mb-3 mx-auto">Sign Up</h2>
                    <div class="signup">

                        <p class="signup__card__text">SignUp to login, Book issue and track progress</p>
                        <hr class="py-2">
                        
                        <div>
                            {% if form.non_field_errors %}
                                <div class="alert alert-danger" role="alert">
                                    {{ form.non_field_errors }}
                                </div>
                            {% endif%}
                        </div>
                        <div class="signup__form mb-3">
                            <form method="POST">
                                {% csrf_token %}
                                
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                  <div class="input-group-text" id="btnGroupAddon"><i class="bi bi-person-fill"></i></div>
                                </div>
                                         
                                        
                                        <input id="id_full_name" type="text" name="full_name" placeholder="Full Name" class="form-control {% if form.full_name.errors %}is-invalid{% endif %}">
                                        <div class="invalid-feedback">
                                           {{ form.full_name.errors}}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                  <div class="input-group-text" id="btnGroupAddon"><i class="bi bi-person-fill"></i></div>
                                </div>
                                         
                                        
                                        <input id="id_username" type="text" name="username" placeholder="Username" class="form-control {% if form.username.errors %}is-invalid{% endif %}">
                                        <div class="invalid-feedback">
                                           {{ form.username.errors}}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                  <div class="input-group-text" id="btnGroupAddon"><i class="bi bi-telegram"></i></div>
                                </div>

                                      
                                        <input id="id_email" type="email" name="email" placeholder="Email" class="form-control {% if form.email.errors %}is-invalid{% endif %}">
                                                        <div class="invalid-feedback">
                                                            {{ form.email.errors}}
                                                        </div>
                                    </div>
                                </div>
                                
                                
                                <div class="form-group">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                  <div class="input-group-text" id="btnGroupAddon"><i class="bi bi-key-fill"></i></div>
                                </div>
                                       
                                        <input id="id_password1" type="password" name="password1" placeholder="Password" class="form-control {% if form.password1.errors %}is-invalid{% endif %}">
                                        <div class="invalid-feedback">
                                            {{ form.password1.errors}}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group pb-2">
                                    <div class="input-group">
                                        <div class="input-group-prepend">
                                  <div class="input-group-text" id="btnGroupAddon"><i class="bi bi-key-fill"></i></div>
                                </div>
                                        
                                        <input id="id_password2" type="password" name="password2" placeholder="Confirm Password" class="form-control {% if form.password2.errors %}is-invalid{% endif %}">
                                        <div class="invalid-feedback">
                                            {{ form.password2.errors}}
                                        </div>
                                    </div>
                                </div>
            
                                <div class="my-4 mx-auto text-center">
                                    <button class="btn btn-sm auth__btn">Sign up</button>
                                </div>
                            </form>
                        </div>
                        <div class="text-center my-1">
                            <p class="or__text">OR</p>
                        </div>
                        <div class="my-2 mx-auto text-center social-btn ">
                            
                        <p class="terms__conditions my-2">By signing up, you agree to our <strong>Terms</strong> , <strong>Data Policy</strong> and <strong>Cookies Policy</strong> .</p>
                    </div>
                </div>
            </div>
            <div class="text-center mt-2 px-5 mx-auto ">
                <p class="have__an__account py-3">Already have an account? <a href="{% url 'signin_view' %}" class="text-decoration-none">Sign in</a></p>

            </div>
        </div>
    </div>
</div>

{% endblock %}